_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "/home/dy20/OWOD-v2/output/t2_baseline/model_final.pth"
DATASETS:
  TRAIN: ('t2_voc_coco_2007_train', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (100000, 120000)
  MAX_ITER: 140000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2_baseline"
OWOD:
  PREV_INTRODUCED_CLS: 20
  CUR_INTRODUCED_CLS: 20
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
  ENABLE_CLUSTERING: False